# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shuquan's Blog
email: shuquan.huang@live.com
description: > # this means to ignore newlines until "baseurl:"
  No hell below us, Above us only sky.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shuquan.github.io/" # the base hostname & protocol for your site
twitter_username: syucyun
github_username:  shuquan

# Build settings
markdown: kramdown

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed


